title: Anmol Goyal
description: CS Freshman | Computer Systems
url: "https://anmol-goyal7.github.io"
baseurl: "" # <--- THIS IS THE MOST IMPORTANT CHANGE (Must be empty)
markdown: kramdown

# footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Â© 2025 Anmol Goyal. Theme by Ankit Sultana."

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/" # Changed from "/researcher/" to "/"
  - name: "Contact"
    link: "/contact/" # Changed from "contact" to "/contact/" for better stability
