title: Anmol Goyal
description: CS Freshman | Computer Systems
url: "https://github.com"
baseurl: "/researcher" # Change to "" if you rename the repo to your-username.github.io
markdown: kramdown

# footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Â© 2025 Anmol Goyal. Theme by Ankit Sultana."

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/researcher/" # Make sure this matches the baseurl above
  - name: "Contact"
    link: "contact"
