title: Anmol Goyal
url: "https://anmol-goyal7.github.io/"
baseurl: "/researcher"

tracking_id: #

footer: yes
footer_url: "https://github.com/anmol-goyal7a"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass


