title: Anmol Goyal
description: CS Freshman | Computer Systems
url: "https://anmol-goyal7.github.io"
baseurl: ""
markdown: kramdown

# footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Â© 2025 Anmol Goyal. Theme by Ankit Sultana."

sass:
    style: compressed
    sass_dir: _sass

# Navigation is empty so nothing appears in the top right
nav: []
