title: Anmol Goyal
description: CS Freshman | Computer Systems
url: "https://anmol-goyal7.github.io"
baseurl: ""
markdown: kramdown

# footer: yes
footer_url: "https://maturk.github.io/"
footer_text: "Â© 2025 Anmol Goyal. Template credits: <a href='https://maturk.github.io/'>Matias Turkulainen</a>."

sass:
    style: compressed
    sass_dir: _sass

# Navigation is empty
nav: []
